services:
  - type: web
    name: coven-zero-bot
    env: node
    plan: free
    rootDir: bot
    buildCommand: npm install && npm run register
    startCommand: npm run start
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: GUILD_ID
        sync: false
      - key: PORT
        value: "3000"
        
