services:
  - type: web
    name: welcomefairydiscordbot
    runtime: node
    env: node
    plan: free
    region: oregon
    buildCommand: "npm ci"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        value: "1402591776321310761"
      - key: GUILD_ID
        value: "1387751793496297522"
      - key: ALTAR_CHANNEL_ID
        value: "1408339354862096446"
      - key: WELCOME_CHANNEL_ID
        value: "1387751793496297528"
      - key: DISCORD_INVITE
        value: "https://discord.gg/7zUDTZmm"
