services:
  # --- Discord Bot (Node Web Service) ---
  - type: web
    name: coven-zero-bot
    env: node
    plan: free
    rootDir: bot
    buildCommand: npm install && npm run register
    startCommand: npm run start
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: GUILD_ID
        sync: false
      - key: PORT
        value: "3000"

  # --- Static Site (Front-end) ---
  - type: static
    name: coven-zero-site
    rootDir: site
    # If you're not running a build (pure static), leave buildCommand empty:
    buildCommand: ""
    staticPublishPath: "."
