services:
  - type: web
    name: welcomfairydiscordbot
    runtime: node
    rootDir: .        # <-- repo root containing package.json
    region: oregon
    plan: free
    buildCommand: >
      bash -lc 'set -e;
      node -v;
      if [ -f package-lock.json ]; then
        echo "[build] lockfile found → npm ci";
        npm ci --no-audit --no-fund || (echo "[build] ci failed → fallback to npm install" && npm install --no-audit --no-fund);
      else
        echo "[build] no lockfile → npm install";
        npm install --no-audit --no-fund;
      fi'
    startCommand: "npm start"
    postDeployCommand: "npm run register"
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        value: "1402591776321310761"
      - key: GUILD_ID
        value: "1387751793496297522"
      - key: ALTAR_CHANNEL_ID
        value: "1408339354862096446"
      - key: WELCOME_CHANNEL_ID
        value: "1387751793496297528"
      - key: DISCORD_INVITE
        value: "https://discord.gg/7zUDTZmm"
