services:
  - type: web
    name: welcomefairydiscordbot
    runtime: node
    buildCommand: "npm ci"
    startCommand: "npm start"
    postDeployCommand: "npm run register"
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        value: "YOUR_APP_CLIENT_ID"
      - key: GUILD_ID
        value: "YOUR_GUILD_ID"
